I = imread('C:\Program Files\MATLAB\R2021b\toolbox\images\imdata\eight.tif');
J = imnoise(I,'salt & pepper',0.02);
figure(),imshow(I);
saveas(gcf,'picture_1.png');
figure(),imshow(J);
saveas(gcf,'picture_2.png');
k1 = filter2(fspecial('average',3),J);
k2 = filter2(fspecial('average',5),J);
k3 = filter2(fspecial('average',7),J);
k4 = filter2(fspecial('average',9),J);
figure(),imshow(uint8(k1));
saveas(gcf,'picture_3.png');
figure(),imshow(uint8(k2));
saveas(gcf,'picture_4.png');
figure(),imshow(uint8(k3));
saveas(gcf,'picture_5.png');
figure(),imshow(uint8(k4));
saveas(gcf,'picture_6.png');
