I = imread('C:\Program Files\MATLAB\R2021b\toolbox\images\imdata\eight.tif');
J = imnoise(I,'salt & pepper',0.02);
figure(),imshow(I);
saveas(gcf,'picture_1.png');
figure(),imshow(J);
saveas(gcf,'picture_2.png');
k1 = medfilt2(J);
k2 = medfilt2(J,[5 5]);
k3 = medfilt2(J,[7 7]);
k4 = medfilt2(J,[9 9]);
figure(),imshow(uint8(k1));
saveas(gcf,'picture_3.png');
figure(),imshow(uint8(k2));
saveas(gcf,'picture_4.png');
figure(),imshow(uint8(k3));
saveas(gcf,'picture_5.png');
figure(),imshow(uint8(k4));
saveas(gcf,'picture_6.png');
